In [54]:
import pandas as pd

print("Resume Screening Project Started")

Resume Screening Project Started

In [ ]:
import os
print(os.getcwd())

c:\Users\msrk2\OneDrive\Documents\FUTURE_ML_03\notebooks

In [ ]:
df = pd.read_csv(r"C:\Users\msrk2\OneDrive\Documents\FUTURE_ML_03\data\Resume\Resume.csv")
df.head()

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [ ]:
import os
os.chdir(r"C:\Users\msrk2\OneDrive\Documents\FUTURE_ML_03")

In [ ]:
df = pd.read_csv("data/Resume/Resume.csv")

In [ ]:
import os
print(os.getcwd())

C:\Users\msrk2\OneDrive\Documents\FUTURE_ML_03

In [ ]:
df = pd.read_csv(r"C:\Users\msrk2\OneDrive\Documents\FUTURE_ML_03\data\Resume\Resume.csv")

In [ ]:
df.head()

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [ ]:
df.columns

Index(['ID', 'Resume_str', 'Resume_html', 'Category'], dtype='str')

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2484 entries, 0 to 2483
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           2484 non-null   int64
 1   Resume_str   2484 non-null   str
 2   Resume_html  2484 non-null   str
 3   Category     2484 non-null   str
dtypes: int64(1), str(3)
memory usage: 77.8 KB

In [ ]:
import re

def clean_text(text):
    text = str(text)
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    text = text.lower()
    text = text.split()
    text = " ".join(text)
    return text

In [ ]:
df['cleaned_text'] = df['Resume_str'].apply(clean_text)

In [ ]:
df[['cleaned_text']].head()

                                        cleaned_text
0  hr administrator marketing associate hr admini...
1  hr specialist us hr operations summary versati...
2  hr director summary over years experience in r...
3  hr specialist summary dedicated driven and dyn...
4  hr manager skill highlights hr skills hr depar...

In [ ]:
df.columns

Index(['ID', 'Resume_str', 'Resume_html', 'Category', 'cleaned_text'], dtype='str')

In [ ]:
skills = [
    "python", "java", "c++", "sql", "excel",
    "machine learning", "deep learning", "nlp",
    "tensorflow", "pytorch", "pandas", "numpy",
    "data analysis", "statistics", "communication"
]

In [ ]:
def extract_skills(text):
    text = str(text).lower()
    found_skills = []

    for skill in skills:
        if skill in text:
            found_skills.append(skill)

    return found_skills

In [ ]:
df['skills'] = df['cleaned_text'].apply(extract_skills)

In [ ]:
df[['cleaned_text', 'skills']].head()

,cleaned_text,skills
0,hr administrator marketing associate hr admini...,"[data analysis, statistics]"
1,hr specialist us hr operations summary versati...,[communication]
2,hr director summary over years experience in r...,[excel]
3,hr specialist summary dedicated driven and dyn...,"[excel, communication]"
4,hr manager skill highlights hr skills hr depar...,[excel]

In [ ]:
from collections import Counter

all_skills = sum(df['skills'], [])
Counter(all_skills).most_common(10)

[('excel', 1616),
 ('communication', 1505),
 ('sql', 191),
 ('statistics', 139),
 ('data analysis', 126),
 ('java', 98),
 ('python', 40),
 ('machine learning', 12),
 ('pandas', 5),
 ('tensorflow', 3)]

In [ ]:
job_description = """
We are looking for a Python developer with experience in machine learning,
data analysis, SQL, and NLP. Candidate should know pandas, numpy, and
basic deep learning concepts.
"""

In [ ]:
job_clean = clean_text(job_description)
job_clean

'we are looking for a python developer with experience in machine learning data analysis sql and nlp candidate should know pandas numpy and basic deep learning concepts'

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
documents = df['cleaned_text'].tolist()
documents.append(job_clean)

In [ ]:
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(documents)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
job_vector = tfidf_matrix[-1]
resume_vectors = tfidf_matrix[:-1]

In [ ]:
scores = cosine_similarity(resume_vectors, job_vector)
df['score'] = scores

In [ ]:
df = df.sort_values(by='score', ascending=False)
df[['cleaned_text', 'skills', 'score']].head(10)

,cleaned_text,skills,score
1762,engineering and quality technician career over...,"[python, sql, excel, machine learning, pandas,...",0.176973
926,software developer professional summary enthus...,"[python, java, sql, excel, tensorflow, pandas,...",0.156873
1339,data analyst professional summary industrial a...,"[python, sql, excel, pandas, numpy, data analy...",0.155923
2153,corporate banking assistant intern objective d...,"[python, sql, machine learning]",0.148135
1218,pavithra shetty summary customer oriented prin...,"[python, java, sql, machine learning, data ana...",0.145836
2291,online learning coordinator program training a...,[],0.141236
1142,consultant summary college graduate with inter...,"[java, sql, excel, communication]",0.134111
243,director of information technology profile sum...,[sql],0.127457
929,vp principal summary i am highly skilled growt...,"[python, java, sql, pandas]",0.127098
2130,market analyst promoted to assistant director ...,"[excel, communication]",0.124878

In [ ]:
df[['skills', 'score']].head(10)

                                                 skills     score
1762  [python, sql, excel, machine learning, pandas,...  0.176973
926   [python, java, sql, excel, tensorflow, pandas,...  0.156873
1339  [python, sql, excel, pandas, numpy, data analy...  0.155923
2153                    [python, sql, machine learning]  0.148135
1218  [python, java, sql, machine learning, data ana...  0.145836
2291                                                 []  0.141236
1142                  [java, sql, excel, communication]  0.134111
243                                               [sql]  0.127457
929                         [python, java, sql, pandas]  0.127098
2130                             [excel, communication]  0.124878

In [ ]:
job_skills = extract_skills(job_clean)
job_skills

['python',
 'sql',
 'machine learning',
 'deep learning',
 'nlp',
 'pandas',
 'numpy',
 'data analysis']

In [ ]:
def skill_gap(candidate_skills, job_skills):
    candidate_skills = set(candidate_skills)
    job_skills = set(job_skills)

    missing = job_skills - candidate_skills
    matched = job_skills & candidate_skills

    return list(matched), list(missing)

In [ ]:
df['matched_skills'] = df['skills'].apply(lambda x: skill_gap(x, job_skills)[0])
df['missing_skills'] = df['skills'].apply(lambda x: skill_gap(x, job_skills)[1])

In [ ]:
df[['skills', 'matched_skills', 'missing_skills', 'score']].head(10)

,skills,matched_skills,missing_skills,score
1762,"[python, sql, excel, machine learning, pandas,...","[machine learning, pandas, python, sql, data a...","[numpy, nlp, deep learning]",0.176973
926,"[python, java, sql, excel, tensorflow, pandas,...","[sql, pandas, python]","[nlp, deep learning, machine learning, numpy, ...",0.156873
1339,"[python, sql, excel, pandas, numpy, data analy...","[pandas, python, sql, numpy, data analysis]","[machine learning, nlp, deep learning]",0.155923
2153,"[python, sql, machine learning]","[python, sql, machine learning]","[nlp, deep learning, pandas, numpy, data analy...",0.148135
1218,"[python, java, sql, machine learning, data ana...","[machine learning, sql, data analysis, python]","[numpy, pandas, nlp, deep learning]",0.145836
2291,[],[],"[nlp, deep learning, machine learning, pandas,...",0.141236
1142,"[java, sql, excel, communication]",[sql],"[nlp, deep learning, machine learning, pandas,...",0.134111
243,[sql],[sql],"[nlp, deep learning, machine learning, pandas,...",0.127457
929,"[python, java, sql, pandas]","[sql, pandas, python]","[nlp, deep learning, machine learning, numpy, ...",0.127098
2130,"[excel, communication]",[],"[nlp, deep learning, machine learning, pandas,...",0.124878

In [ ]:
df.to_csv("output/ranked_candidates.csv", index=False)

In [ ]:
import os
print(os.listdir("output"))

['ranked_candidates.csv']

In [ ]:
df['score']

1762    0.176973
926     0.156873
1339    0.155923
2153    0.148135
1218    0.145836
          ...
130     0.007042
2349    0.006797
1852    0.006281
153     0.002374
656     0.000000
Name: score, Length: 2484, dtype: float64

In [ ]:
df['score_percent'] = df['score'] * 100

In [ ]:
df['score_percent'] = (df['score'] * 100).round(2)

In [ ]:
df['score_percent'] = (df['score'] * 100).round(0).astype(int)

In [ ]:
df['score_label'] = (df['score'] * 100).round(1).astype(str) + " %"

In [ ]:
def get_status(score):
    if score >= 70:
        return "🟢 Highly Recommended"
    elif score >= 40:
        return "🟡 Moderate Match"
    else:
        return "🔴 Low Match"

In [ ]:
df['status'] = df['score_percent'].apply(get_status)

In [ ]:
import streamlit as st
import pandas as pd

st.set_page_config(page_title="AI Resume Screening", layout="wide")

st.title("📄 AI Resume Screening System")

df = pd.read_csv("output/ranked_candidates.csv")

df['score_percent'] = (df['score'] * 100).round(1)

def get_status(score):
    if score >= 70:
        return "🟢 Highly Recommended"
    elif score >= 40:
        return "🟡 Moderate Match"
    else:
        return "🔴 Low Match"

df['status'] = df['score_percent'].apply(get_status)

st.subheader("Top Ranked Candidates")

st.dataframe(
    df[['skills', 'score_percent', 'status', 'missing_skills']],
    use_container_width=True
)

2026-06-07 15:04:48.235 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:04:48.237 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:04:48.674
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run c:\Users\msrk2\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-06-07 15:04:48.675 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:04:48.676 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:04:49.736 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:04:49.737 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:04:49.738 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:04:49.799 Please replace `use_container_width` with `width`.

`use_container_width` will be removed after 2025-12-31.

For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.
2026-06-07 15:04:49.836 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:04:49.838 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:04:49.840 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

DeltaGenerator()

In [ ]:
st.subheader("Match Score Visualization")

for i, row in df.iterrows():
    st.write(row['skills'])
    st.progress(int(row['score_percent']))
    st.write(row['status'])

2026-06-07 15:06:17.375 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.377 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.378 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.387 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.388 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.389 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.391 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.392 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.393 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.395 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.397 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.398 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.400 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.401 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.403 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.404 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.405 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.406 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.408 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.409 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.410 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.412 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.413 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.415 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.416 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.417 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.418 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.420 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.421 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.424 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.426 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.427 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.429 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.430 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.432 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.433 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.435 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.436 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.438 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.440 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.442 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.443 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.445 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.447 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.448 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.450 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.452 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.453 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.455 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.456 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.457 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.458 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.464 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.470 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.471 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.473 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.474 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.476 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.479 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.480 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.481 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.482 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.483 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.485 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.486 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.488 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.489 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.490 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.493 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.497 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.499 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.501 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.502 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.503 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.505 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.506 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.509 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.511 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.514 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.515 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.516 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.517 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.518 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.519 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.521 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.522 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.523 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.528 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.533 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.539 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.541 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.545 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.547 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.549 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.550 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.551 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.552 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.553 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.554 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.555 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.556 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.559 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.567 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.569 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.570 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.571 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.573 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.574 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.581 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.583 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.585 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.586 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.588 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.589 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.590 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.592 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.594 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.597 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.600 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.601 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.602 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.604 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.605 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.606 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.613 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.621 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.623 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.624 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.629 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.631 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.632 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.635 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.651 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.658 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.664 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.668 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.671 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.672 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.674 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.679 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.687 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.691 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.697 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.701 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.703 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.705 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.706 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.710 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.714 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.716 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.719 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.721 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.722 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.723 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.724 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.726 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.728 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-07 15:06:17.729 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [ ]:
df.to_csv("output/ranked_candidates.csv", index=False)

In [2]:
df = df.head(10)

NameError: name 'df' is not defined

In [4]:
import pandas as pd

df = pd.read_csv(r"C:\Users\msrk2\OneDrive\Documents\FUTURE_ML_03\output\ranked_candidates.csv")

print(df.columns.tolist())

['ID', 'Resume_str', 'Resume_html', 'Category', 'cleaned_text', 'skills', 'score', 'matched_skills', 'missing_skills', 'score_percent', 'status']

In [6]:
# Final ranking

ranked_df = df.sort_values("score", ascending=False)

ranked_df.to_csv(
    "output/ranked_candidates.csv",
    index=False
)

print("Saved successfully!")

OSError: Cannot save file into a non-existent directory: 'output'